import os
import json
from model_connect import call_llm

DB_FOLDER = "database_mock"


def load_agent1_data(project_name: str) -> dict:
    """Loads the raw data generated by Agent 1 from the database."""
    db_filepath = os.path.join(DB_FOLDER, project_name, "db_document.json")
    if not os.path.exists(db_filepath):
        raise FileNotFoundError(f"No database document found for '{project_name}'. Please run Agent 1 first.")

    with open(db_filepath, "r", encoding="utf-8") as f:
        return json.load(f)


def save_agent2_data(project_name: str, original_doc: dict, agent2_insights: dict):
    """Updates the database document with Agent 2's output."""
    db_filepath = os.path.join(DB_FOLDER, project_name, "db_document.json")

    original_doc["agent2_output"] = agent2_insights
    original_doc["processing_status"]["agent2_insights_extracted"] = True

    with open(db_filepath, "w", encoding="utf-8") as f:
        json.dump(original_doc, f, indent=4, ensure_ascii=False)

    print(f"✅ [SUCCESS] Agent 2 insights saved to DB for {project_name}")


def run_agent2(project_name: str, provider: str = "gemini_2"):
    print(f"\n[AGENT 2] Starting Insight Extraction for: {project_name.upper()}\n")

    # 1. Load Data
    print("-> Loading raw signals from database...")
    db_doc = load_agent1_data(project_name)
    raw_data_sources = db_doc.get("data_sources", {})

    # We convert the entire raw dictionary to a JSON string.
    # Because Gemini has a 1M+ token window, it can read all the reviews, reddit posts, and transcripts easily.
    raw_data_str = json.dumps(raw_data_sources, ensure_ascii=False)

    print(f"-> Sending {len(raw_data_str)} characters of raw data to {provider.upper()}...")

    # 2. Define the precise System Prompt matching your specifications
    system_prompt = """
    You are a Senior Product Researcher and Founder's Assistant.
    Your objective is to convert messy, raw data (competitor tracking, user conversations, reviews, internal notes) 
    into structured, validated user problems and patterns.

    CORE PRINCIPLES:
    1. Focus on Signal Over Noise. Discard generic comments.
    2. Group similar problems together. Do not list 10 identical complaints; group them into one core issue.
    3. Base EVERYTHING on the provided evidence. Do not invent or hallucinate data.

    OUTPUT SCHEMA:
    You must output a JSON object containing a list of "problems" exactly matching this structure:
    {
      "problems": [
        {
          "problem": "Clear, concise description of the user issue",
          "evidence": ["Exact quote or summary from source 1", "Quote 2"],
          "frequency": "Low" | "Medium" | "High",
          "user_type": "Beginner" | "Intermediate" | "Advanced" | "Unknown",
          "source_mix": ["Play Store", "Reddit", "Competitor"]
        }
      ]
    }
    """

    # 3. Define the User Prompt
    user_prompt = f"""
    Analyze the following raw data collected for the project '{project_name}'.
    Identify the most critical user problems, complaints, and gaps.

    RAW DATA:
    {raw_data_str}
    """

    # 4. Call the LLM
    print("-> Analyzing patterns and grouping problems (this may take a moment)...")
    response_text = call_llm(
        prompt=user_prompt,
        system_prompt=system_prompt,
        provider=provider,
        json_mode=True
    )

    # 5. Parse and Save
    try:
        # Clean up the response in case the LLM wrapped it in markdown
        if "```json" in response_text:
            response_text = response_text.split("```json")[1].split("```")[0].strip()
        elif "```" in response_text:
            response_text = response_text.split("```")[1].split("```")[0].strip()

        insights_json = json.loads(response_text)

        save_agent2_data(project_name, db_doc, insights_json)

        print("\n--- AGENT 2 EXTRACTION SUMMARY ---")
        print(f"Found {len(insights_json.get('problems', []))} core validated problems.")

    except Exception as e:
        print(f"❌ [ERROR] Failed to parse LLM response into JSON: {e}")
        print(f"Raw Response: {response_text}")


# ==========================================
# INTERACTIVE CLI RUNNER
# ==========================================
if __name__ == "__main__":
    print("=" * 60)
    print("  AGENT 2: INSIGHT EXTRACTION")
    print("=" * 60)

    target_project = input("Enter Project Name to analyze (must exist in database_mock/): ").strip()

    if target_project:
        run_agent2(target_project, provider="gemini")
    else:
        print("Project name required.")